DailyEnglish01/Models/ErrorViewModel.cs
namespace DailyEnglish01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DailyEnglish01/Models/QuoteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DailyEnglish01
{
    public class QuoteModel
    {
        [DisplayName("Id Number")]
        public int Id { get; set; }
        [DisplayName("Author Name")]
        public string Author { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionTr { get; set; }
    }
}

DailyEnglish01/Controllers/HomeController.cs
using DailyEnglish01.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DailyEnglish01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DailyEnglish01/Controllers/QuotesController.cs
using DailyEnglish01.Models;
using DailyEnglish01.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
namespace DailyEnglish01.Controllers
{
    public class QuotesController : Controller
    {
        // GET: QuotesController
        //public ActionResult Index(int p  = 1)
        //{
        //    QuoteService quotes = new QuoteService();
        //    return View(quotes.GetAllQuotes().ToPagedList(p, 4));
        //    //List<Quote> Quotes = new List<Quote>();
        //    //Quotes.Add(new Quote { Id = 0, Author = "mehmet", DescriptionEn = "hello", DescriptionTr="merhaba" });
        //    //Quotes.Add(new Quote { Id = 1, Author = "filiz", DescriptionEn = "ben", DescriptionTr = "me" });
        //    //Quotes.Add(new Quote { Id = 2, Author = "kerem", DescriptionEn = "namjfdf jfaksdfşsd jfke  jkej ekjf  jşdsfasdf jkdjfasdfw kşdjfasse", DescriptionTr = "isim" });
        //    //Quotes.Add(new Quote { Id = 3, Author = "ali", DescriptionEn = "school", DescriptionTr = "okul" });
        //    //return View(Quotes);
        //}
        public ActionResult Index() 
        {
            QuotesDAO quotes = new QuotesDAO();
            return View(quotes.GetAllQuotes());
            //List<Quote> Quotes = new List<Quote>();
            //Quotes.Add(new Quote { Id = 0, Author = "mehmet", DescriptionEn = "hello", DescriptionTr="merhaba" });
            //Quotes.Add(new Quote { Id = 1, Author = "filiz", DescriptionEn = "ben", DescriptionTr = "me" });
            //Quotes.Add(new Quote { Id = 2, Author = "kerem", DescriptionEn = "namjfdf jfaksdfşsd jfke  jkej ekjf  jşdsfasdf jkdjfasdfw kşdjfasse", DescriptionTr = "isim" });
            //Quotes.Add(new Quote { Id = 3, Author = "ali", DescriptionEn = "school", DescriptionTr = "okul" });
            //return View(Quotes);
        }
        public IActionResult SearchForm()
        {
            return View();
        }
        public IActionResult SearchResults(string searchTerm)
        {
            QuotesDAO quote = new QuotesDAO();
            List<QuoteModel> quoteList = quote.SearchQuotes(searchTerm);
            return View("index", quoteList);
        }
        // GET: QuotesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuotesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuotesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuotesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuotesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuotesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuotesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DailyEnglish01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Daily English</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DailyEnglish01/Views/Quotes/Index.cshtml
@model IEnumerable<DailyEnglish01.QuoteModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<h2>Daily English Quotes List</h2>
<div class="container d-flex flex-wrap">
    @foreach (var item in Model)
    {
        <div class="card col-6 text-justify">
            <div class="card-header">
                <p class="card-text">@item.Id</p>
            </div>
            <div class="card-body">
                <h5 class="card-text">"@item.DescriptionEn"</h5>
                <p class="card-text">"@item.DescriptionTr"</p>
                <h6 class="card-title">-@item.Author</h6>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    }
</div>
@*@Html.PagedListPager((IPagedList)Model,p=>Url.Action("Index", new {p}), new PagedListRenderOptions{
    LiElementClasses = new List<string>
    {"page-link"}
})*@

DailyEnglish01/Views/Quotes/SearchForm.cshtml
<h4>Search Quotes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchResults">
            <div class="form-group">
                <label class="control-label">Search for a Author</label>
                <input name="searchTerm" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DailyEnglish01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DailyEnglish01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DailyEnglish01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_navbar.cshtml")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DailyEnglish01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DailyEnglish01/Views/Shared/_navbar.cshtml
<nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DailyEnglish01</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="Index">Quotes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>
</nav>